### ISSUE TITLE
Turkey

### ISSUE THREAD

**Issue by thielj** [Danilka/covid-estimator#1]
15,776,664 estimated vs. 1,236 reported cases as of Mar 23.
Estimation confidence: High

Doesn't make sense to me!

**Comment by Danilka** [comment]
That's what the model predicts. Turkey reported the following spike in deaths recently:
0 | 1 | 1 | 3 | 4 | 9 | 30
This points at a very steep growth curve. It will adjust as more data comes in.

Here is some info on how this is calculated: https://medium.com/@danilka/there-are-more-coronavirus-cases-than-you-think-6fa2fed50355

**Comment by thielj** [comment]
compared to other nations, it rather hints to a delay (or maybe even censorship) in reporting

**Comment by Danilka** [comment]
The delay between cases growth and deaths is 19 days in my model. Others point to as low as 12, but there is definitely a delay.
In a lot of countries, especially with a lot of low-quality healthcare, lots of deaths will be attributed to other diseases, like standard pneumonia. That's why such estimates could also be way off.

**Comment by Danilka** [comment]
Feel free to open a new issue if needed.
